web:
    image: wordpress
    links:
        - db:mysql
    ports:
        - 127.0.3.1:80:80
    volumes:
        - ./var/www/html:/var/www/html

db:
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    volumes:
        - ./var/lib/mysql:/var/lib/mysql
